/*
*    Description : Class to show implementation of abstract methods 
*
*    Version        Author            Date            Description
*  
*    1.0            Kaajal Bhawale    03/03/2015      Initial Draft
*/

public class ImplementAbstractMethod extends AbstarctClass{

    public override void abstractMethod(){
        system.debug('Now in Abstarct Method Implementation');
    }//end of abstract method

}